import { readFile, writeFile } from 'fs/promises'
import { existsSync } from 'fs'
import { join } from 'path'

const ENV_FILE = join(process.cwd(), '.env')
const ENV_EXAMPLE_FILE = join(process.cwd(), '.env.example')
const CONFIG_EXAMPLE_FILE = join(process.cwd(), 'pocketping.config.example.ts')

/**
 * Parse the contents of a dotenv file into a key/value map.
 *
 * Tolerates the common real-world shapes the previous naive regex missed:
 *   - `export KEY=value` prefixes
 *   - single- or double-quoted values
 *   - values that themselves contain `=` (e.g. base64, URLs with query strings)
 *   - blank lines and `#` comments
 *   - surrounding whitespace
 */
export function parseEnvContent(content: string): Record<string, string> {
  const vars: Record<string, string> = {}
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue

    const withoutExport = line.startsWith('export ') ? line.slice(7).trim() : line
    const eq = withoutExport.indexOf('=')
    if (eq === -1) continue

    const key = withoutExport.slice(0, eq).trim()
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue

    let value = withoutExport.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    vars[key] = value
  }
  return vars
}

/** Read and parse a dotenv file. Returns an empty map if the file is absent. */
export async function loadEnv(path: string = ENV_FILE): Promise<Record<string, string>> {
  if (!existsSync(path)) return {}
  return parseEnvContent(await readFile(path, 'utf-8'))
}

export async function saveEnvFile(newVars: Record<string, string>): Promise<void> {
  let existingContent = ''

  // Read existing .env if it exists
  if (existsSync(ENV_FILE)) {
    existingContent = await readFile(ENV_FILE, 'utf-8')
  }

  // Parse existing variables
  const existingVars = parseEnvContent(existingContent)

  // Merge with new variables (new ones override)
  const mergedVars = { ...existingVars, ...newVars }

  // Generate new content with sections
  const sections: Record<string, string[]> = {
    '# PocketPing Configuration': [],
    '# Discord': [],
    '# Slack': [],
    '# Telegram': [],
    '# Other': [],
  }

  for (const [key, value] of Object.entries(mergedVars)) {
    if (key.startsWith('DISCORD_')) {
      sections['# Discord'].push(`${key}=${value}`)
    } else if (key.startsWith('SLACK_')) {
      sections['# Slack'].push(`${key}=${value}`)
    } else if (key.startsWith('TELEGRAM_')) {
      sections['# Telegram'].push(`${key}=${value}`)
    } else {
      sections['# Other'].push(`${key}=${value}`)
    }
  }

  // Build output
  const lines: string[] = ['# PocketPing Configuration', `# Generated by: npx @pocketping/cli init`, '']

  for (const [header, vars] of Object.entries(sections)) {
    if (vars.length > 0 && header !== '# PocketPing Configuration') {
      lines.push(header)
      lines.push(...vars)
      lines.push('')
    }
  }

  await writeFile(ENV_FILE, lines.join('\n'))

  // Write a .env.example with placeholder values — but never clobber an
  // existing one (it may be hand-maintained and committed to the repo).
  if (!existsSync(ENV_EXAMPLE_FILE)) {
    const exampleLines = lines.map((line) => {
      if (line.includes('TOKEN=') || line.includes('SECRET=')) {
        return line.replace(/=.+$/, '=your_token_here')
      }
      return line
    })
    await writeFile(ENV_EXAMPLE_FILE, exampleLines.join('\n'))
  }
}

export async function generateConfigExample(bridges: string[]): Promise<void> {
  const imports: string[] = []
  const bridgeInits: string[] = []
  const bridgeRefs: string[] = []

  if (bridges.includes('discord')) {
    imports.push('DiscordBridge')
    bridgeInits.push(`const discord = DiscordBridge.bot({
  botToken: process.env.DISCORD_BOT_TOKEN!,
  channelId: process.env.DISCORD_CHANNEL_ID!,
})`)
    bridgeRefs.push('discord')
  }

  if (bridges.includes('slack')) {
    imports.push('SlackBridge')
    bridgeInits.push(`const slack = SlackBridge.bot({
  botToken: process.env.SLACK_BOT_TOKEN!,
  channelId: process.env.SLACK_CHANNEL_ID!,
})`)
    bridgeRefs.push('slack')
  }

  if (bridges.includes('telegram')) {
    imports.push('TelegramBridge')
    bridgeInits.push(`const telegram = TelegramBridge.bot({
  botToken: process.env.TELEGRAM_BOT_TOKEN!,
  chatId: process.env.TELEGRAM_CHAT_ID!,
})`)
    bridgeRefs.push('telegram')
  }

  const content = `/**
 * PocketPing Configuration Example
 * Generated by: npx @pocketping/cli init
 *
 * Copy this to your project and customize as needed.
 */

import { PocketPing, ${imports.join(', ')} } from '@pocketping/sdk-node'

// Initialize bridges
${bridgeInits.join('\n\n')}

// Create PocketPing instance
export const pocketping = new PocketPing({
  bridges: [${bridgeRefs.join(', ')}],
})

// Example: Handle a new visitor message
// pocketping.onVisitorMessage(async (message, session) => {
//   console.log('New message:', message.content)
// })

// Example: Handle operator reply
// pocketping.onOperatorMessage(async (message, session) => {
//   // Send to your widget/frontend
// })
`

  await writeFile(CONFIG_EXAMPLE_FILE, content)
}
